// src/lib/components/footer/Search.svelte
<input type="text" placeholder="Suchen" {oninput} />

<style>
  input {
    border: none;
    padding: 0 0.5em;
    font-size: 1em;
    border-radius: var(--border-radius);
    background-color: var(--color-background--light);
    color: var(--color-font);
  }
</style>

<script lang="ts">
  import filterStore from '$lib/stores/filter/filterStore';

  function oninput(event: any) {
    const searchTerm = ((event as InputEvent).target! as HTMLInputElement).value;
    filterStore.search(searchTerm);
  }
</script>

// components/ui/search.vue
<template>
  <div class="search-wrapper">
    <input type="text" class="search-input" placeholder="Suche ..." @input="onSearchInput" />
  </div>
</template>

<script setup lang="ts">
import { useFilterStore } from '@/stores/filter';

const filterStore = useFilterStore();

function onSearchInput(event: InputEvent) {
  const value = (event.target as HTMLInputElement).value;
  filterStore.$patch({ searchTerm: value });
}
</script>

<style>
.search-wrapper {
  flex-grow: 1;
  display: flex;
  align-items: center;
  justify-content: center;
}

.search-input {
  flex-grow: 1;
  border: 1px solid var(--color-font--dark);
  background-color: var(--color-background--light);
  color: var(--color-font);
  border-radius: 100px;
  padding:0 .75em;
}

.search-input:focus-visible {
  outline: none;
  border-color: var(--color-primary);
}
</style>
